### ISSUE TITLE
unresolved identifier when using srfi-189

### ISSUE THREAD

**Issue by CMB** [Zipheir/srfi-189-chicken#1]
I have a typescript file showing two uses of either-let*:
one in the interpreter, and one in a module that is to be compiled.
The interpreted code works but complains.
The module doesn't compile because payload-exception is unresolved.

Here's a link to my paste on paste.call-cc.org.

**Comment by CMB** [comment]
http://paste.call-cc.org/paste?id=fddf60f15c9ddbc7b75ea7cd3278e762b372b95e

**Comment by Zipheir** [comment]
Patch applied and released in 1.0.3. Thanks.
